version: '3.3'
services:
  nosql-db:
    image: mongo
    ports:
      - 27018:27017
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    command: npm start
    container_name: products
    ports:
      - 8002:8002
    restart: always
    depends_on:
      - 'nosql-db'
    volumes:
      - .:/app
      - /app/products/node_modules

    env_file:
      - ./products/.env.dev
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    command: npm start
    container_name: shopping
    ports:
      - 8003:8003
    restart: always
    depends_on:
      - 'nosql-db'
    volumes:
      - .:/app
      - /app/shopping/node_modules
    env_file:
      - ./shopping/.env.dev
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    command: npm start
    container_name: customer
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - 'nosql-db'

    volumes:
      - .:/app/
      - /app/customer/node_modules
    env_file:
      - ./customer/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 90:90
